name: PR

on: pull_request

jobs:
  git:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git log
      run: |
        git fetch --prune --unshallow
        MESSAGE=`git log --pretty=format:%s -n2 | tail -n1`
        SKIP_CI=`contains($MESSAGE, '[skip ci]')`
        echo ""::set-env name=SKIP_CI::$SKIP_CI"

  skip-ci:
    if: ${{ env.SKIP_CI }}
    runs-on: ubuntu-latest

    steps:
    - name: skip?
      run: echo "not skip"
