name: PR

on: pull_request

jobs:
  git:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Git log
      run: |
        git fetch --prune --unshallow
        if [[ ${{ github.event.after == "" }} ]]; then
          echo 'without github.event.after'
          MESSAGE=`git log --pretty=format:%s -n2 | tail -n1`
        else
          echo 'with github.event.after'
          MESSAGE=`git log --pretty=format:%s -n1 ${{ github.event.after }}`
        fi
        echo MESSAGE
    - name: set true
      run: echo '::set-env name=ENV_TEST::true'
    - name: CI
      if: ${{ env.ENV_TEST }}
      run: echo 'ENV_TEST is true'
    - name: not CI
      if: ${{ !env.ENV_TEST }}
      run: echo 'ENV_TEST is false'
